### PR TITLE
Achydra 867 featured partner info pages

### PR DESCRIPTION
**Pull request by ej2432**
I've added the proper routing for the link to the Featured Partners page from the FAQ page, line 131 of app/views/info/faq.html.erb.

Apologies if I should have done something differently to create this pull request. I stuck with my original local branch.

### CODE REVIEW

**Comment by ej2432** [comment]
I missed this conflict note, apologies. I'll work to resolve this next Monday.

**Comment by ej2432** [comment]
Hello again. I have reviewed the conflicts, and the version of faq.html.erb associated with this pull request is the correct one. How can I best resolve this conflict? Sorry for any confusion.

**Comment by ej2432** [comment]
@JackBlackLight , I resolved the conflicts on this branch via github. However, now this pull request is only showing one file as changed... Did I do this incorrectly?

**Comment by JackBlackLight** [comment]
Hi @ej2432, I'm not sure how many changed files were on this branch before the merge, but it may be that some of the changes you made are already in the master branch. You could review those files in your PR branch to make sure they have the changes you want now, and that merging master didn't overwrite them. 

For example, it looks like this change
https://github.com/ej2432/ac-academiccommons/commit/d175f892d92169de7a96301fbfefc5eaca6befc9
is already in the AC master branch
https://github.com/cul/ac-academiccommons/blob/master/app/models/concerns/academic_commons/desc_metadata.rb#L193
(It looks like that change was merged 9 months ago in a branch of yours related to AC-879)

Let me know if you have any more questions.

**Comment by ej2432** [comment]
Thanks, @JackBlackLight . I went back over all the changes and compared to master, and it looks like this is the only file that is different after all of that. Which is good! Thank you.

**Comment by ej2432** [comment]
@JackBlackLight , would you be willing to review this PR at your convenience? Thank you!

**Pull request merged**
